"""Layer 24: generate the heterogeneous source-system fixtures the ETL ingests.

Reads the frozen `scenarios/*/*.json` (the ground-truth documents) via the Pydantic models,
pools every entity by primary key, and re-emits the same data as *deliberately divergent*
source-system files under `source_systems/`:

    erp/purchase_orders.csv   erp/invoices.csv    (aliased headers, $/decimal money, mixed dates)
    carrier/asn_856.txt                            (856-ish loops, UOM synonyms, split shipment)
    wms/receiving.json                             (nested keys, UOM synonyms, whitespace, mixed dates)
    portal/claims_<lot-date>.json                  (one file per daily lot; nested keys, mixed dates)
    tpm/trade_agreements.json                      (nested keys, mixed dates)
    manifest.json                                  (file -> format/target/lot_date; the load contract)

The divergences are applied *deterministically* (even/odd row index picks the format) so the
output is reproducible — the committed `source_systems/` tree can be regenerated byte-for-byte,
and every divergence is exactly reversible so the Layer 27 fidelity oracle (DB == frozen JSON)
holds. This is a one-off dev script; ETL parsing lives in `semantic_layer/` from Layer 25 on.

Run: `python -m tools.generate_source_systems [--out DIR]`.
"""

import argparse
import csv
import io
import json
from pathlib import Path

from mcp_server.models import (
    ASN,
    DeductionClaim,
    Invoice,
    PurchaseOrder,
    ReceivingRecord,
    TradeAgreement,
)

REPO_ROOT = Path(__file__).parent.parent
SCENARIOS_ROOT = REPO_ROOT / "scenarios"
DEFAULT_OUT = REPO_ROOT / "source_systems"

# Canonical UOM -> carrier/WMS synonym (EACH/CASE/PALLET -> EA/CS/PLT). Transform folds it back.
UOM_SYNONYM = {"EACH": "EA", "CASE": "CS", "PALLET": "PLT"}


# --- divergence helpers (each exactly reversible) ------------------------------------------------

def _dollars(cents: int, dollar_sign: bool) -> str:
    """Integer cents -> decimal string, e.g. 250 -> '2.50' / '$2.50' (no float, exact reverse)."""
    text = f"{cents // 100}.{cents % 100:02d}"
    return f"${text}" if dollar_sign else text


def _date(iso: str, mm_dd_yyyy: bool) -> str:
    """ISO 'YYYY-MM-DD' -> 'MM/DD/YYYY' when mm_dd_yyyy else unchanged (components stay padded)."""
    if not mm_dd_yyyy:
        return iso
    year, month, day = iso.split("-")
    return f"{month}/{day}/{year}"


# --- pooling -------------------------------------------------------------------------------------

class Pool:
    """Entities pooled by PK across all scenarios, plus the per-lot claim split."""

    def __init__(self) -> None:
        self.purchase_orders: dict[str, PurchaseOrder] = {}
        self.invoices: dict[str, Invoice] = {}
        self.asns: dict[str, ASN] = {}
        self.receiving: dict[str, ReceivingRecord] = {}
        self.agreements: dict[str, TradeAgreement] = {}
        self.active_claims: dict[str, DeductionClaim] = {}  # deduction_claim.json -> today's lot
        self.prior_claims: dict[str, DeductionClaim] = {}   # prior_claim.json -> earlier lots


def _put(bucket: dict, key: str, value) -> None:
    """Insert deduping by PK; a same-PK conflict across scenarios is a fixture bug, so raise."""
    if key in bucket and bucket[key] != value:
        raise ValueError(f"conflicting rows for primary key {key!r}: {bucket[key]} vs {value}")
    bucket[key] = value


def pool_entities() -> Pool:
    pool = Pool()
    for scenario_dir in sorted(SCENARIOS_ROOT.iterdir()):
        if not scenario_dir.is_dir():
            continue
        po = PurchaseOrder.model_validate_json((scenario_dir / "po.json").read_text())
        _put(pool.purchase_orders, po.po_id, po)
        inv = Invoice.model_validate_json((scenario_dir / "invoice.json").read_text())
        _put(pool.invoices, inv.invoice_id, inv)
        rcp = ReceivingRecord.model_validate_json(
            (scenario_dir / "receiving_record.json").read_text()
        )
        _put(pool.receiving, rcp.receipt_id, rcp)
        for asn_path in sorted(scenario_dir.glob("asn*.json")):
            asn = ASN.model_validate_json(asn_path.read_text())
            _put(pool.asns, asn.asn_id, asn)
        ta_path = scenario_dir / "trade_agreement.json"
        if ta_path.exists():
            ta = TradeAgreement.model_validate_json(ta_path.read_text())
            _put(pool.agreements, ta.agreement_id, ta)
        active = DeductionClaim.model_validate_json(
            (scenario_dir / "deduction_claim.json").read_text()
        )
        _put(pool.active_claims, active.claim_id, active)
        prior_path = scenario_dir / "prior_claim.json"
        if prior_path.exists():
            prior = DeductionClaim.model_validate_json(prior_path.read_text())
            _put(pool.prior_claims, prior.claim_id, prior)
    return pool


# --- writers -------------------------------------------------------------------------------------

def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def _write_json(path: Path, obj) -> None:
    _write_text(path, json.dumps(obj, indent=2, ensure_ascii=False) + "\n")


def _write_csv(path: Path, header: list[str], rows: list[list]) -> None:
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")  # QUOTE_MINIMAL default; '\n' for git-stable bytes
    writer.writerow(header)
    writer.writerows(rows)
    _write_text(path, buf.getvalue())


def write_erp_purchase_orders(out: Path, pool: Pool) -> None:
    header = ["PO_NUMBER", "RETAILER", "ITEM", "QTY", "UOM", "UNIT_PRICE", "ORDER_DT"]
    rows = []
    for i, po in enumerate(sorted(pool.purchase_orders.values(), key=lambda p: p.po_id)):
        even = i % 2 == 0
        rows.append([
            po.po_id, po.retailer, po.sku, po.ordered_qty, po.ordered_uom,
            _dollars(po.unit_price, even), _date(po.order_date, even),
        ])
    _write_csv(out / "erp" / "purchase_orders.csv", header, rows)


def write_erp_invoices(out: Path, pool: Pool) -> None:
    header = ["INVOICE_NO", "PO_NUMBER", "ITEM", "QTY", "UOM", "AMOUNT", "INVOICE_DT"]
    rows = []
    for i, inv in enumerate(sorted(pool.invoices.values(), key=lambda x: x.invoice_id)):
        even = i % 2 == 0
        rows.append([
            inv.invoice_id, inv.po_id, inv.sku, inv.invoiced_qty, inv.invoiced_uom,
            _dollars(inv.amount, even), _date(inv.invoice_date, even),
        ])
    _write_csv(out / "erp" / "invoices.csv", header, rows)


def write_carrier_asns(out: Path, pool: Pool) -> None:
    blocks = []
    for asn in sorted(pool.asns.values(), key=lambda a: a.asn_id):
        blocks.append("\n".join([
            f"ASN*{asn.asn_id}*{asn.po_id}",
            f"ITEM*{asn.sku}*{asn.shipped_qty}*{UOM_SYNONYM[asn.shipped_uom]}",
            f"SHIP*{asn.ship_date}*{asn.carrier}",
        ]))
    _write_text(out / "carrier" / "asn_856.txt", "\n\n".join(blocks) + "\n")


def write_wms_receiving(out: Path, pool: Pool) -> None:
    records = []
    for i, rcp in enumerate(sorted(pool.receiving.values(), key=lambda r: r.receipt_id)):
        even = i % 2 == 0
        records.append({"receipt": {
            "id": rcp.receipt_id,
            "po": rcp.po_id,
            "item": rcp.sku,
            "qtyReceived": rcp.received_qty,
            "uom": UOM_SYNONYM[rcp.received_uom],
            "date": _date(rcp.receipt_date, even),
            "lot": rcp.lot_id,
            "notes": f"  {rcp.notes}  ",  # padded to exercise Transform trimming
        }})
    _write_json(out / "wms" / "receiving.json", records)


def write_tpm_agreements(out: Path, pool: Pool) -> None:
    records = []
    for i, ta in enumerate(sorted(pool.agreements.values(), key=lambda a: a.agreement_id)):
        even = i % 2 == 0
        records.append({"agreement": {
            "id": ta.agreement_id,
            "retailer": ta.retailer,
            "sku": ta.sku,
            "promoCode": ta.promo_code,
            "terms": ta.discount_terms,
            "validFrom": _date(ta.valid_from, even),
            "validTo": _date(ta.valid_to, even),
            "signedBy": ta.signed_by,
        }})
    _write_json(out / "tpm" / "trade_agreements.json", records)


def _write_portal_lot(out: Path, lot_date: str, claims: list[DeductionClaim]) -> None:
    records = []
    for i, claim in enumerate(sorted(claims, key=lambda c: c.claim_id)):
        even = i % 2 == 0
        records.append({
            "claimId": claim.claim_id,
            "po": claim.po_id,
            "retailer": claim.retailer,
            "reason": claim.claimed_reason,
            "amount": _dollars(claim.claimed_amount, even),
            "claimDate": _date(claim.claim_date, even),
            "notes": claim.retailer_notes,  # verbatim: preserves the injection surface byte-exact
        })
    _write_json(out / "portal" / f"claims_{lot_date}.json", {"lot_date": lot_date, "claims": records})


def portal_lots(pool: Pool) -> dict[str, list[DeductionClaim]]:
    """Map lot_date -> claims. Today's lot = the active claims (dated by their latest claim_date);
    each prior claim gets its own earlier lot dated by its own claim_date."""
    lots: dict[str, list[DeductionClaim]] = {}
    active = list(pool.active_claims.values())
    today_lot_date = max(c.claim_date for c in active)
    lots[today_lot_date] = active
    for prior in pool.prior_claims.values():
        lots.setdefault(prior.claim_date, []).append(prior)
    return lots


def write_portal_claims(out: Path, pool: Pool) -> list[str]:
    lots = portal_lots(pool)
    for lot_date, claims in lots.items():
        _write_portal_lot(out, lot_date, claims)
    return sorted(lots)


def write_manifest(out: Path, portal_lot_dates: list[str]) -> None:
    sources = [
        {"file": "erp/purchase_orders.csv", "format": "erp_csv", "target": "purchase_orders"},
        {"file": "erp/invoices.csv", "format": "erp_csv", "target": "invoices"},
        {"file": "carrier/asn_856.txt", "format": "carrier_856", "target": "asns"},
        {"file": "wms/receiving.json", "format": "wms_json", "target": "receiving_records"},
        {"file": "tpm/trade_agreements.json", "format": "tpm_json", "target": "trade_agreements"},
    ]
    for lot_date in portal_lot_dates:
        sources.append({
            "file": f"portal/claims_{lot_date}.json",
            "format": "portal_json",
            "target": "deduction_claims",
            "lot_date": lot_date,
        })
    _write_json(out / "manifest.json", {"sources": sources})


def generate(out: Path) -> None:
    pool = pool_entities()
    write_erp_purchase_orders(out, pool)
    write_erp_invoices(out, pool)
    write_carrier_asns(out, pool)
    write_wms_receiving(out, pool)
    write_tpm_agreements(out, pool)
    lot_dates = write_portal_claims(out, pool)
    write_manifest(out, lot_dates)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate heterogeneous source-system fixtures.")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output dir (default: source_systems/)")
    args = parser.parse_args()
    generate(args.out)
    print(f"Wrote source-system fixtures to {args.out}")


if __name__ == "__main__":
    main()
